### ISSUE TITLE
Usar el namespace `NainLobato\RFC`.

### ISSUE THREAD

**Issue by eclipxe13** [NainLobato/rfc#1]
Es una buena práctica para las librerías de PHP poner el namespace como `Vendor\Proyecto`. De esta manera se evitan colisiones entre el implementador y otros paquetes con el mismo nombre que tampoco sigan el estándar.

En este proyecto el namespace principal es `RFC`, la propuesta es renombrarlo a `NainLobato\RFC`.

Para hacerlo se tendrían que cambiar los archivos fuente y el archivo `composer.json`, si gustas puedo ayudarte con este cambio aprovechando que aún no se ha creado un primer release.

**Comment by NainLobato** [comment]
Hola, me vendría bien tu ayuda amigo.
